---
swagger: '2.0'
info:
  title: Classic API Resource Documentation
  description: |
    <h1>Log in to see the full documentation</h1>
    <form action="https://hackingo.youbike.be" method="post">
    <label for="email">Login:</label>
    <input name="email">
    <label for="password">Password:</label>
    <input name="password">
    <input type="submit" value="Login"></form><!--
  version: production
basePath: https://hackingo.youbike.be
produces:
- application/xml
- application/json
consumes:
- application/xml
- application/json
security:
- basicAuth: []
paths:
  "/test":
    get:
      responses:
        '200':
          description: No response was specified
      tags:
      - sometext
      operationId: findAccounts
      summary: this is example text
  "/malformed_by_afine":
    delete:
      parameters:
      - description: |
          <noscript>

        format: int64
        in: path
        name: id
        required: true
        type: integer
      responses:
        '200':
          description: No response was specified
      tags:
      - test
      operationId: test
      summary: test
    get:
      parameters:
      - description: this is example text
        format: int64
        in: path
        name: id
        required: true
        type: integer
      responses:
        '200':
          description: No response was specified
      tags:
      - s1rn3tz
      operationId: some_operation
      summary: this is example text